### ISSUE TITLE
Compiler error (conversation from IRC)

### ISSUE THREAD

**Issue by abl** [jgrayillustrate/microlens_for_pebble#1]
jgray424> Did anyone check out my github repo yesterday? I had a question about a compiler error I was getting: https://github.com/jgrayillustrate/microlens_for_pebble

Go ahead and add detail here and, as time permits, I'll take a look at it for you.

P.S. You might want to sign up for IRCCloud (which is what I use) or run your own IRC bouncer - I keep responding to you when you're not in the channel.

**Comment by jgrayillustrate** [comment]
@abl Thanks so much! I'll look into IRCCloud since that sounds very helpful.

The error I was getting was basically "undefined reference to `microlens_init' collect2: error: ld returned 1 exit status".

**Comment by jgrayillustrate** [comment]
@abl - thanks for your willingness to help. I'm new to C and I think I found the problem - line 22 in microlens.c - thanks again!

**Comment by abl** [comment]
Nice, glad to see you got it :D

IRCCloud is $5/month, but for that you get nice (at least I like 'em) web and mobile clients.

If you already have a server somewhere, setting up ZNC is pretty easy, and with the right plugins you can also get push notifications, etc.
